services:

  mysql:
    image: mysql:8.0
    container_name: smart_report_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: smart_report_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: smart_report_backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    depends_on:
      mysql:
        condition: service_healthy

      redis:
        condition: service_started


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smart_report_frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend


volumes:
  mysql_data:
  redis_data:
